import Head from 'next/head'
// import Image from 'next/image'
import Articles from '../components/Articles'
import styles from '../styles/Home.module.css'

export default function Home({ articles }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Articles articles={articles} />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/articles');
  const articles = await res.json();

  return {
    props: {
      articles
    }
  }
}